/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    application
}

repositories {
    val githubOwner = (findProperty("github.owner") as String?) ?: System.getenv("GITHUB_OWNER")
    val githubRepo = (findProperty("github.repo") as String?) ?: System.getenv("GITHUB_REPO")

    val githubPackagesUrl =
        if (!githubOwner.isNullOrBlank() && !githubRepo.isNullOrBlank()) {
            "https://maven.pkg.github.com/$githubOwner/$githubRepo"
        } else {
            logger.warn(
                "GitHub Packages repo not configured; set github.owner/github.repo in ~/.gradle/gradle.properties " +
                    "or GITHUB_OWNER/GITHUB_REPO env vars (example: OWNER/REPO).",
            )
            "https://maven.pkg.github.com/OWNER/REPO"
        }

    maven {
        url = uri(githubPackagesUrl)
        credentials {
            username = (findProperty("gpr.user") as String?) ?: System.getenv("GITHUB_ACTOR")
            password = (findProperty("gpr.key") as String?) ?: System.getenv("GITHUB_TOKEN")
        }
    }

    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("com.amazonaws:aws-lambda-java-core:1.2.3")
    implementation("com.amazonaws:aws-lambda-java-events:3.11.5")
    implementation("software.amazon.awssdk:dynamodb:2.25.66")
    implementation("software.amazon.awssdk:auth:2.25.66")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.17.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2")
    implementation("com.alex:autonomo-control-core:1.0.0")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = "autonomo.local.LocalRunnerKt"
}
